#234408bc773a3c62c99ad0ebceb82e505b49ca2b4511a8aa6b03e47c089dac4e85e5659e032668b20a25eceb88f77d0476197b616bb209063469c085c9c95701
#production:
#secret_key_base: ENV['SECRET_KEY_BASE']

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  active_merchant_login: <%= ENV["AM_LOGIN"] %>
  active_merchant_password: <%= ENV["AM_PASSWORD"] %>